export { default as Hero } from "./01Hero";
export { default as Skills } from "./02Skills";
export { default as Website } from "./03Website";
export { default as AdManager } from "./04AdManager";
export { default as GradientGenerator } from "./05GradientGenerator";
export { default as Ecommerce } from "./06Ecommerce";
export { default as DeliveryFeeCalculator } from "./07DeliveryFeeCalculator";
export { default as Game } from "./08Game";
export { default as ContactBottom } from "./09ContactBottom";
