export { default as Hero } from "./Hero";
export { default as Skills } from "./Skills";
export { default as Website } from "./Website";
export { default as AdManager } from "./AdManager";
export { default as GradientGenerator } from "./GradientGenerator";
export { default as Ecommerce } from "./Ecommerce";
export { default as DeliveryFeeCalculator } from "./DeliveryFeeCalculator";
export { default as Game } from "./Game";
export { default as ContactBottom } from "./ContactBottom";
